name: CI - Release - Docker Container Image

on:
  push:
    tags:
      - 'v*'  # Runs when a tag like v0.1.0 is pushed
  release:
    types: [published]  # Also runs when a GitHub release is published
  workflow_dispatch:  # Allows manual builds, tagged with the short commit SHA

jobs:
  docker-build-and-push:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    with:
      output: image
      push: ${{ github.event_name != 'pull_request' }}
      platforms: linux/amd64,linux/arm64
      file: build/Dockerfile
      cache: true
      cache-mode: max
      meta-images: ghcr.io/${{ github.repository }}
      meta-tags: |
        type=ref,event=branch
        type=ref,event=tag
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=sha,format=short
        type=raw,value=latest,enable={{is_default_branch}}
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

